### ISSUE TITLE
Migrate Common Voice data

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/commonvoice-it#9]
Missing files:
- [ ] CommonVoice-Data/names.py (needs data from a Italian source, and properly patched to be able to parse italian data) #4 
- [ ] CommonVoice-Data/libretheatre.py (needs data from Italian source, maybe has to be rewritten entirely) #5
- [X] CommonVoice-Data/wikipedia.py (done)
- [ ] CommonVoice-Data/wikisource.py (needs italian translation of the book "Le forceures de blocus", has to be rewritten to be able to scrap the italian book) #5
- [ ] CommonVoice-Data/framabook.py #5
- [ ] CommonVoice-Data/utils.py (needs to be adapted to italian language)

_Originally posted by @alex179ohm in https://github.com/MozillaItalia/commonvoice-it/issues/2#issuecomment-530848048_
